mcscript
nyu-mll/jiant pull request #1152
Opened 2020-10-13 18:59 UTC by wh629

I'm having issues running black. I spoke with Jason and am submitting the PR without black.

Changes tested with the attached .sh and .sbatch files. Achieved 86.5% dev accuracy and found 86.6% from https://www.aclweb.org/anthology/D19-6012.pdf.

[mcscript.zip](https://github.com/nyu-mll/jiant/files/5373524/mcscript.zip)

2020-10-13 18:59 UTC, pep8speaks commented
Hello @wh629! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`jiant/tasks/lib/mcscript.py`](https://github.com/nyu-mll/jiant/blob/ca82240570ad26da12e38dc65f3a02777ce0b5ce/jiant/tasks/lib/mcscript.py):

> [Line 8:1](https://github.com/nyu-mll/jiant/blob/ca82240570ad26da12e38dc65f3a02777ce0b5ce/jiant/tasks/lib/mcscript.py#L8): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 64:46](https://github.com/nyu-mll/jiant/blob/ca82240570ad26da12e38dc65f3a02777ce0b5ce/jiant/tasks/lib/mcscript.py#L64): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 64:50](https://github.com/nyu-mll/jiant/blob/ca82240570ad26da12e38dc65f3a02777ce0b5ce/jiant/tasks/lib/mcscript.py#L64): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 64:101](https://github.com/nyu-mll/jiant/blob/ca82240570ad26da12e38dc65f3a02777ce0b5ce/jiant/tasks/lib/mcscript.py#L64): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 100 characters)
> [Line 65:101](https://github.com/nyu-mll/jiant/blob/ca82240570ad26da12e38dc65f3a02777ce0b5ce/jiant/tasks/lib/mcscript.py#L65): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 100 characters)



You can repair most issues by installing [black](https://github.com/ambv/black) and running: `black -l 100 ./*`. If you contribute often, have a look at the 'Contributing' section of the [README](https://github.com/nyu-mll/jiant) for instructions on doing this automatically.

2020-10-16 04:44 UTC, zphang commented on jiant/tasks/lib/mcscript.py
> +        return MCScriptTask
I think this is a vestige of some previous code that required tracing examples->tasks, but I can't remember what it is. (E.g. it's also in `hellaswag`).

2020-10-16 04:47 UTC, zphang requested changes
Removing the task property method, and add to 
https://github.com/nyu-mll/jiant-dev/blob/master/md_docs/tasks.md

2020-10-18 19:58 UTC, wh629 commented
@SimonOst

2020-10-22 00:06 UTC, jeswan approved these changes

2020-10-22 17:01 UTC, zphang approved these changes

2020-10-22 17:01 UTC, merged