Adding download code for ARCT, MCTest, MCTACO, MuTual, and QuAIL
nyu-mll/jiant pull request #1258
Opened 2021-01-05 03:41 UTC by claravania

This PR adds download code for the following tasks: arct, mctest160, mctest600, mctaco, mutual, mutual_plus, and quail. Besides quail which uses HF datasets, all tasks used direct download links.

Tested using the following command:
```
export PYTHONPATH=jiant/
python jiant/jiant/scripts/download_data/runscript.py download --tasks [TASK_NAME] --output_path [OUTPUT_PATH]
```

2021-01-05 17:28 UTC, jeswan commented on jiant/scripts/download_data/dl_datasets/files_tasks.py
> +                "train_ans": os.path.join(task_data_path, "mc160.train.ans"),
Is the following suitable for the task? I want to try and reduce the number of named keys in a task config (`*_ans` is a new key).
```suggestion
                "train_labels": os.path.join(task_data_path, "mc160.train.ans"),
```

2021-01-05 17:35 UTC, jeswan commented on jiant/tasks/lib/quail.py
> +                    choice_list=["answers"],
Should this be `line["answers"]`?

2021-01-05 17:38 UTC, jeswan commented on jiant/tasks/lib/quail.py
> +                    choice_list=["answers"],
```suggestion
                    choice_list=[d for d in line["answers"]]
```

2021-01-05 17:40 UTC, jeswan requested changes
One concern about QuAIL (see comment). Will approve after this concern and formatting is addressed.

2021-01-05 21:12 UTC, claravania commented
@jeswan I've fixed the QuAIL and reformat issues.

2021-01-06 17:42 UTC, jeswan approved these changes

2021-01-07 19:18 UTC, merged